/* MODELAGEM DE CLIENTE */

CREATE DATABASE COMERCIO;

USE COMERCIO;

CREATE TABLE CLIENT(
	IDCLIENT INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(30) NOT NULL,
	GENDER ENUM('M','F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE
);

CREATE TABLE PHONE(
	ID_PHONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO UNUM('COM','RES','CEL'),
	NUMERO VARCHAR(10)
);

CREATE TABLE ADDRESS(
	ID_ADDRESS INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL;
);
	
	/*AINDA NAO COLOQUEI NO MYSQL