/* WHAT I WHANNA DO? */
A TABLE WITH
CLIENT
	NAME CARACTER(30)
	GENDER CARACTER(1)
	EMAIL CARACTER(30)
	CPF INT(11)
	PHONE CARACTER(11)
	ADDRESS CARACTER(100)
	
/* CREATING DATABESE PROJECT */

CREATE DATABASE PROJECT1;

/* TO USE DATABASE AND CREATE TABLE FOR EXAMPLE */

USE PROJECT1;

/* CREATING TABLE */

CREATE TABLE CLIENT(
	NAME VARCHAR(30),
	GENDER CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	PHONE VARCHAR(11),
	ADDRESS VARCHAR(100)
);

/* MOSTRANDO TABELAS */

SHOW TABLES;

/* DESCRIBLE STRUCTURE OF THE TABLE */

DESC CLIENT;

/* INSERTING VALUES */

INSERT INTO CLIENT VALUES('JOAO','M', 'JOAO@GMAIL.COM',698569741,'11985986521','RUA DAS BELEZAS - CENTRO - SP');
INSERT INTO CLIENT VALUES(
	'CELIA',
	'F',
	'CELIA@GMAIL.COM',
	156987463,
	'11998745632',
	'VILA DAS BELEZA - PARQUE BELEM - RJ'
);
INSERT INTO CLIENT VALUES('JORGE', 'M', NULL, 886593269, '11986532697', 'OSCAR FREIRE - CENTRO - MG');
INSERT INTO CLIENT(NAME,GENDER,ADDRESS,PHONE,CPF) 
VALUES('LILIAN','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ', '11985234678', 985698532);
INSERT INTO CLIENT VALUES
	('ANA','F','ANA@GLOBO.COM',896523548,"11985632487",'PRES ANTONIO CAROS - SAO PAULO - SP'),
	('CARLA','F','CARLA@TERRA.COM',856326489,'11956326598','SAMUEL SILVA - CENTRO - BELO HORINZONTE - MG');
INSERT INTO CLIENT VALUES('MARCELA', 'F', NULL, 886593269, '11986532697', 'POLI - BAIRRO DOS PIMENTAS - SAO PAULO - SP');

/* SELECT */

SELECT NOW();
SELECT 'MARCELA' AS 'MEU AMOR';
SELECT NAME,GENDER,EMAIL FROM CLIENT;

/* WHERE */

SELECT NAME, ADDRESS FROM CLIENT WHERE GENDER ='M';
SELECT NAME, ADDRESS FROM CLIENT WHERE GENDER ='F';
/* LIKE */
SELECT NAME, ADDRESS FROM CLIENT WHERE ADDRESS LIKE '%RJ';

/* AND & OR*/

SELECT NAME, EMAIL, ADDRESS FROM CLIENT
WHERE GENDER='F' AND ADDRESS LIKE '%SP';

SELECT NAME, ADDRESS, EMAIL, GENDER FROM CLIENT
WHERE GENDER='M' OR ADDRESS LIKE '%SP';

/* COUNT */
 
SELECT COUNT(*) FROM CLIENT;
SELECT COUNT(*) AS 'QUANTIDADE DE ITENS DA TABELA' FROM CLIENT;

SELECT GENDER, COUNT(*) AS 'QUANTIDADE' FROM CLIENT
GROUP BY GENDER;

SELECT EMAIL, COUNT(*) AS 'QUANTIDADE' FROM CLIENT
GROUP BY EMAIL;

/* NOT */

SELECT NAME, EMAIL FROM CLIENT WHERE GENDER NOT LIKE "F";
SELECT NAME, EMAIL FROM CLIENT WHERE GENDER NOT LIKE "M";

SELECT NAME, EMAIL FROM CLIENT WHERE EMAIL IS NOT NULL;

/* UPDATE */

UPDATE CLIENT
SET EMAIL = 'MARCELAFMELLO07@GMAIL.COM'
WHERE NAME='MARCELA';

/* DELETE*/

DELETE FROM CLIENT
WHERE NAME ='ANA';

UPDATE CLIENT
SET  PHONE='11956892314'
WHERE NAME='JOAO';

SELECT ADDRESS, COUNT(*) AS 'QUANTIDADE'
FROM CLIENT
GROUP BY ADDRESS;

/* PRIMEIA FORMA NORMAL */


/*
1- TODO CAMPOS VETORIZADO SE TORNARA UMA TABELA2

2- TODO CAMPO MULTIVALORADO SE TORNARA OUTRA TABELA

3-TODA TABELA NECESSITA DE AO MENOS UM CAMPO QUE 
REGISTRE TODO REGISTRO COMO SENDO UNICO - PRIMARY KEY
bANCO





